{% set name = "django-denied" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-denied-{{ version }}.tar.gz
  sha256: 217ba6568c2a63c0284215c840a4b67cb959407d90f077ff068f0e5d4351912d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - django >=3.2
    - python >=3.7

test:
  imports:
    - denied
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mblayman/django-denied
  summary: An authorization system based exclusively on allow lists
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
