{% set name = "django-denied" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-denied-{{ version }}.tar.gz
  sha256: 15a5f3a5de47a88a366c53d4eaca9af9a4b6679739f2a0dca3971c78b7657381

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - django >=3.2
    - python >=3.7

test:
  imports:
    - denied
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mblayman/django-denied
  summary: An authorization system based exclusively on allow lists
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
